version: '3'

services:
  syncer:
    image: syncer_image
    volumes:
      - /Users/jimvincentwagner/.credentials:/root/.credentials
    environment:
      NOTION_TOKEN: secret_dBMfuT28DpqZNV56NrFFY4N0VvVCHNtHrmelLwkZkvj
      NOTION_DATABASE_ID: 2f0c689557c34340b85379ab5fc363d8
      GMAIL_ADDRESS: jimvwagner@gmail.com
